export const BASE_PERMISSION = {
  'table|manage': true,
  'table|import': true,
  'table|export': true,
  'base|delete': true,
  'base|read': true,
  'base|read_all': true,
  'base|update': true,
  'base|invite_email': true,
  'base|invite_link': true,
  'base|table_import': true,
  'base|table_export': true,
  'base|db_connection': true,
  'base|query_data': true,
};
