[phases.setup]
nixPkgs = ["nodejs_20", "glibc", "gcc", "gnumake", "python3", "git"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[phases.start]
cmd = "pnpm start"