/* eslint-disable @typescript-eslint/naming-convention */
import type { Action } from '../actions';
import { Role, type IRole } from './types';

export const RolePermission: Record<IRole, Record<Action, boolean>> = {
  [Role.Owner]: {
    'table|read': true,
    'table|manage': true,
    'table|import': true,
    'table|export': true,
    'view|create': true,
    'view|delete': true,
    'view|update': true,
    'record|create': true,
    'record|delete': true,
    'record|update': true,
    'user|email_read': true,
    'user|manage': true,
  },
  [Role.Creator]: {
    'table|read': true,
    'table|manage': true,
    'table|import': true,
    'table|export': true,
    'view|create': true,
    'view|delete': true,
    'view|update': true,
    'record|create': true,
    'record|delete': true,
    'record|update': true,
    'user|email_read': true,
    'user|manage': true,
  },
  [Role.Editor]: {
    'table|read': true,
    'table|manage': false,
    'table|import': false,
    'table|export': true,
    'view|create': true,
    'view|delete': true,
    'view|update': true,
    'record|create': true,
    'record|delete': true,
    'record|update': true,
    'user|email_read': true,
    'user|manage': false,
  },
  [Role.Commenter]: {
    'table|read': true,
    'table|manage': false,
    'table|import': false,
    'table|export': true,
    'view|create': false,
    'view|delete': false,
    'view|update': false,
    'record|create': false,
    'record|delete': false,
    'record|update': false,
    'user|email_read': true,
    'user|manage': false,
  },
  [Role.Viewer]: {
    'table|read': true,
    'table|manage': false,
    'table|import': false,
    'table|export': true,
    'view|create': false,
    'view|delete': false,
    'view|update': false,
    'record|create': false,
    'record|delete': false,
    'record|update': false,
    'user|email_read': true,
    'user|manage': false,
  },
};
