/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/_error'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as SettingsQueryBuilderRouteImport } from './routes/settings/query-builder'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsDesignRouteImport } from './routes/settings/design'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forget-password'
import { Route as TableTableIdRouteRouteImport } from './routes/table/$tableId/route'
import { Route as TableTableIdViewIdRouteImport } from './routes/table/$tableId/$viewId'
import { Route as DeveloperToolQueryBuilderRouteImport } from './routes/developer/tool/query-builder'
import { Route as ApiMonitorSentryRouteImport } from './routes/api/_monitor/sentry'
import { Route as ApiMonitorHealthcheckRouteImport } from './routes/api/_monitor/healthcheck'
import { Route as MonitorSentrySsrPageRouteImport } from './routes/_monitor/sentry/ssr-page'
import { Route as MonitorSentryCsrPageRouteImport } from './routes/_monitor/sentry/csr-page'
import { Route as MonitorPreviewErrorPageRouteImport } from './routes/_monitor/preview/error-page'

const ErrorRoute = ErrorRouteImport.update({
  id: '/_error',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsQueryBuilderRoute = SettingsQueryBuilderRouteImport.update({
  id: '/settings/query-builder',
  path: '/settings/query-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDesignRoute = SettingsDesignRouteImport.update({
  id: '/settings/design',
  path: '/settings/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/auth/forget-password',
  path: '/auth/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableIdRouteRoute = TableTableIdRouteRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableIdViewIdRoute = TableTableIdViewIdRouteImport.update({
  id: '/$viewId',
  path: '/$viewId',
  getParentRoute: () => TableTableIdRouteRoute,
} as any)
const DeveloperToolQueryBuilderRoute =
  DeveloperToolQueryBuilderRouteImport.update({
    id: '/developer/tool/query-builder',
    path: '/developer/tool/query-builder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMonitorSentryRoute = ApiMonitorSentryRouteImport.update({
  id: '/api/_monitor/sentry',
  path: '/api/sentry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonitorHealthcheckRoute = ApiMonitorHealthcheckRouteImport.update({
  id: '/api/_monitor/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorSentrySsrPageRoute = MonitorSentrySsrPageRouteImport.update({
  id: '/_monitor/sentry/ssr-page',
  path: '/sentry/ssr-page',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorSentryCsrPageRoute = MonitorSentryCsrPageRouteImport.update({
  id: '/_monitor/sentry/csr-page',
  path: '/sentry/csr-page',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorPreviewErrorPageRoute = MonitorPreviewErrorPageRouteImport.update({
  id: '/_monitor/preview/error-page',
  path: '/preview/error-page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/table/$tableId': typeof TableTableIdRouteRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/design': typeof SettingsDesignRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/query-builder': typeof SettingsQueryBuilderRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/preview/error-page': typeof MonitorPreviewErrorPageRoute
  '/sentry/csr-page': typeof MonitorSentryCsrPageRoute
  '/sentry/ssr-page': typeof MonitorSentrySsrPageRoute
  '/api/healthcheck': typeof ApiMonitorHealthcheckRoute
  '/api/sentry': typeof ApiMonitorSentryRoute
  '/developer/tool/query-builder': typeof DeveloperToolQueryBuilderRoute
  '/table/$tableId/$viewId': typeof TableTableIdViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/table/$tableId': typeof TableTableIdRouteRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/design': typeof SettingsDesignRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/query-builder': typeof SettingsQueryBuilderRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/preview/error-page': typeof MonitorPreviewErrorPageRoute
  '/sentry/csr-page': typeof MonitorSentryCsrPageRoute
  '/sentry/ssr-page': typeof MonitorSentrySsrPageRoute
  '/api/healthcheck': typeof ApiMonitorHealthcheckRoute
  '/api/sentry': typeof ApiMonitorSentryRoute
  '/developer/tool/query-builder': typeof DeveloperToolQueryBuilderRoute
  '/table/$tableId/$viewId': typeof TableTableIdViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/_error': typeof ErrorRoute
  '/table/$tableId': typeof TableTableIdRouteRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/design': typeof SettingsDesignRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/query-builder': typeof SettingsQueryBuilderRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/users': typeof SettingsUsersRoute
  '/_monitor/preview/error-page': typeof MonitorPreviewErrorPageRoute
  '/_monitor/sentry/csr-page': typeof MonitorSentryCsrPageRoute
  '/_monitor/sentry/ssr-page': typeof MonitorSentrySsrPageRoute
  '/api/_monitor/healthcheck': typeof ApiMonitorHealthcheckRoute
  '/api/_monitor/sentry': typeof ApiMonitorSentryRoute
  '/developer/tool/query-builder': typeof DeveloperToolQueryBuilderRoute
  '/table/$tableId/$viewId': typeof TableTableIdViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/table/$tableId'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/settings/design'
    | '/settings/general'
    | '/settings/query-builder'
    | '/settings/roles'
    | '/settings/users'
    | '/preview/error-page'
    | '/sentry/csr-page'
    | '/sentry/ssr-page'
    | '/api/healthcheck'
    | '/api/sentry'
    | '/developer/tool/query-builder'
    | '/table/$tableId/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/table/$tableId'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/settings/design'
    | '/settings/general'
    | '/settings/query-builder'
    | '/settings/roles'
    | '/settings/users'
    | '/preview/error-page'
    | '/sentry/csr-page'
    | '/sentry/ssr-page'
    | '/api/healthcheck'
    | '/api/sentry'
    | '/developer/tool/query-builder'
    | '/table/$tableId/$viewId'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/_error'
    | '/table/$tableId'
    | '/auth/forget-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/settings/design'
    | '/settings/general'
    | '/settings/query-builder'
    | '/settings/roles'
    | '/settings/users'
    | '/_monitor/preview/error-page'
    | '/_monitor/sentry/csr-page'
    | '/_monitor/sentry/ssr-page'
    | '/api/_monitor/healthcheck'
    | '/api/_monitor/sentry'
    | '/developer/tool/query-builder'
    | '/table/$tableId/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  ErrorRoute: typeof ErrorRoute
  TableTableIdRouteRoute: typeof TableTableIdRouteRouteWithChildren
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  SettingsDesignRoute: typeof SettingsDesignRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsQueryBuilderRoute: typeof SettingsQueryBuilderRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  MonitorPreviewErrorPageRoute: typeof MonitorPreviewErrorPageRoute
  MonitorSentryCsrPageRoute: typeof MonitorSentryCsrPageRoute
  MonitorSentrySsrPageRoute: typeof MonitorSentrySsrPageRoute
  ApiMonitorHealthcheckRoute: typeof ApiMonitorHealthcheckRoute
  ApiMonitorSentryRoute: typeof ApiMonitorSentryRoute
  DeveloperToolQueryBuilderRoute: typeof DeveloperToolQueryBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_error': {
      id: '/_error'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/query-builder': {
      id: '/settings/query-builder'
      path: '/settings/query-builder'
      fullPath: '/settings/query-builder'
      preLoaderRoute: typeof SettingsQueryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/design': {
      id: '/settings/design'
      path: '/settings/design'
      fullPath: '/settings/design'
      preLoaderRoute: typeof SettingsDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/auth/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableId': {
      id: '/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof TableTableIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableId/$viewId': {
      id: '/table/$tableId/$viewId'
      path: '/$viewId'
      fullPath: '/table/$tableId/$viewId'
      preLoaderRoute: typeof TableTableIdViewIdRouteImport
      parentRoute: typeof TableTableIdRouteRoute
    }
    '/developer/tool/query-builder': {
      id: '/developer/tool/query-builder'
      path: '/developer/tool/query-builder'
      fullPath: '/developer/tool/query-builder'
      preLoaderRoute: typeof DeveloperToolQueryBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/_monitor/sentry': {
      id: '/api/_monitor/sentry'
      path: '/api/sentry'
      fullPath: '/api/sentry'
      preLoaderRoute: typeof ApiMonitorSentryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/_monitor/healthcheck': {
      id: '/api/_monitor/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiMonitorHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_monitor/sentry/ssr-page': {
      id: '/_monitor/sentry/ssr-page'
      path: '/sentry/ssr-page'
      fullPath: '/sentry/ssr-page'
      preLoaderRoute: typeof MonitorSentrySsrPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_monitor/sentry/csr-page': {
      id: '/_monitor/sentry/csr-page'
      path: '/sentry/csr-page'
      fullPath: '/sentry/csr-page'
      preLoaderRoute: typeof MonitorSentryCsrPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_monitor/preview/error-page': {
      id: '/_monitor/preview/error-page'
      path: '/preview/error-page'
      fullPath: '/preview/error-page'
      preLoaderRoute: typeof MonitorPreviewErrorPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TableTableIdRouteRouteChildren {
  TableTableIdViewIdRoute: typeof TableTableIdViewIdRoute
}

const TableTableIdRouteRouteChildren: TableTableIdRouteRouteChildren = {
  TableTableIdViewIdRoute: TableTableIdViewIdRoute,
}

const TableTableIdRouteRouteWithChildren =
  TableTableIdRouteRoute._addFileChildren(TableTableIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  ErrorRoute: ErrorRoute,
  TableTableIdRouteRoute: TableTableIdRouteRouteWithChildren,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  SettingsDesignRoute: SettingsDesignRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsQueryBuilderRoute: SettingsQueryBuilderRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  MonitorPreviewErrorPageRoute: MonitorPreviewErrorPageRoute,
  MonitorSentryCsrPageRoute: MonitorSentryCsrPageRoute,
  MonitorSentrySsrPageRoute: MonitorSentrySsrPageRoute,
  ApiMonitorHealthcheckRoute: ApiMonitorHealthcheckRoute,
  ApiMonitorSentryRoute: ApiMonitorSentryRoute,
  DeveloperToolQueryBuilderRoute: DeveloperToolQueryBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
